version: "3.8" 

services:
  # =====================
  # PRODUCT SERVICE
  # =====================
  product-service:
    build: 
      context: ./product-service
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    environment:
      - DB_HOST=product-db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=productdb
    depends_on:
      - product-db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=product-db", "--user=root", "--password=root"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  product-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=productdb
    volumes:
      - product-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=root"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  # =====================
  # CART SERVICE
  # =====================
  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=cart-db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=cartdb
      - APP_ENV=docker
    depends_on:
      cart-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pg_isready", "--host=cart-db", "--username=postgres", "--dbname=cartdb"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    command: bash -c "echo '‚è≥ Waiting for DB...' && sleep 10 && php artisan migrate && php -S 0.0.0.0:3002 -t public"

  cart-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres  
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=cartdb
    ports:
      - "5432:5432"
    volumes:
      - cart-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=postgres", "--dbname=cartdb"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  
  review-service:
    build:
      context: ./review-service 
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - MONGO_USER=root
      - MONGO_PASSWORD=Dev@root23
      - MONGO_HOST=review-db
    depends_on:
      - review-db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.stats()"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s


  review-db:
    image: mongo:6.0
    container_name: review-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Dev@root23
    volumes:
      - review-db-data:/data/db


volumes:
  product-db-data:
  cart-db-data:
  review-db-data:
